export const TransactionCounterParties = {
  DEPOSIT_SERVICE: 'DEPOSIT_SERVICE',
  SPORTS_EXCHANGE: 'SPORTS_EXCHANGE',
  SPORTSBOOK: 'SPORTSBOOK',
  FUNGAMESS: 'FUNGAMESS',
  MASTER_TOKEN_ISSUE: 'MASTER_TOKEN_ISSUE',
  MASTER_TOKEN_SETTLEMENT: 'MASTER_TOKEN_SETTLEMENT',
  WITHDRAWAL_SERVICE: 'WITHDRAWAL_SERVICE',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
  EVENBET_POKER: 'EVENBET_POKER',
  SLOTEGRATOR_GAMES: 'SLOTEGRATOR_GAMES',
  SLOTEGRATOR_SPORTSBOOK: 'SLOTEGRATOR_SPORTSBOOK',
  COUPON_CODE: 'COUPON_CODE',
  BONUS_CASHBACK: 'BONUS_CASHBACK',
  TIP_BONUS: 'TIP_BONUS',
  WAGERING_BONUS: 'WAGERING_BONUS',
  REWARD: 'REWARD',
} as const;

export type TransactionCounterParty =
  (typeof TransactionCounterParties)[keyof typeof TransactionCounterParties];
