export const TRON_WITHDRAWAL_WALLET_TRX_ALERT_LEVEL =
  'TRON_WITHDRAWAL_WALLET_TRX_ALERT_LEVEL';
export const TRON_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL =
  'TRON_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL';
export const TRON_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL =
  'TRON_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL';
export const TRON_FEES_WALLET_ALERT_LEVEL = 'TRON_FEES_WALLET_ALERT_LEVEL';

export const SOLANA_WITHDRAWAL_WALLET_SOL_ALERT_LEVEL =
  'SOLANA_WITHDRAWAL_WALLET_SOL_ALERT_LEVEL';
export const SOLANA_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL =
  'SOLANA_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL';
export const SOLANA_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL =
  'SOLANA_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL';
export const SOLANA_FEES_WALLET_ALERT_LEVEL = 'SOLANA_FEES_WALLET_ALERT_LEVEL';

export const ETHEREUM_WITHDRAWAL_WALLET_ETH_ALERT_LEVEL =
  'ETHEREUM_WITHDRAWAL_WALLET_ETH_ALERT_LEVEL';
export const ETHEREUM_USDT_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL =
  'ETHEREUM_USDT_WITHDRAWAL_WALLET_USDT_ALERT_LEVEL';
export const ETHEREUM_USDC_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL =
  'ETHEREUM_USDC_WITHDRAWAL_WALLET_USDC_ALERT_LEVEL';
