export const TRON_DEPOSIT_PUBLIC_KEY_SECRET = 'TRON_DEPOSIT_PUBLIC_KEY';
export const TRON_WITHDRAW_PRIVATE_KEY_SECRET = 'TRON_WITHDRAW_PRIVATE_KEY';
export const TRON_WITHDRAW_PUBLIC_KEY_SECRET = 'TRON_WITHDRAW_PUBLIC_KEY';
export const TRON_SETTLEMENT_PUBLIC_KEY_SECRET = 'TRON_SETTLEMENT_PUBLIC_KEY';
export const TRON_FEES_PUBLIC_KEY_SECRET = 'TRON_FEES_PUBLIC_KEY';
export const TRON_FEES_PRIVATE_KEY_SECRET = 'TRON_FEES_PRIVATE_KEY';

export const SOLANA_DEPOSIT_PUBLIC_KEY_SECRET = 'SOLANA_DEPOSIT_PUBLIC_KEY';
export const SOLANA_WITHDRAWAL_PUBLIC_KEY_SECRET = 'SOLANA_WITHDRAW_PUBLIC_KEY';
export const SOLANA_WITHDRAWAL_PRIVATE_KEY_SECRET =
  'SOLANA_WITHDRAW_PRIVATE_KEY';
export const SOLANA_FEES_PUBLIC_KEY_SECRET = 'SOLANA_FEES_PUBLIC_KEY';
export const SOLANA_FEES_PRIVATE_KEY_SECRET = 'SOLANA_FEES_PRIVATE_KEY';

export const ETHEREUM_DEPOSIT_PUBLIC_KEY_SECRET = 'ETHEREUM_DEPOSIT_PUBLIC_KEY';
export const ETHEREUM_WITHDRAWAL_PUBLIC_KEY_SECRET =
  'ETHEREUM_WITHDRAWAL_PUBLIC_KEY';
export const ETHEREUM_WITHDRAWAL_PRIVATE_KEY_SECRET =
  'ETHEREUM_WITHDRAWAL_PRIVATE_KEY';
